--
-- PostgreSQL database dump
--

\restrict RMLZ6aAhBhVduGSDp9MwqVJYyhfMoVQ2HVO6HeZ9xLMViYdOC1jXA2EX6ZSJ5sl

-- Dumped from database version 16.14
-- Dumped by pg_dump version 16.14

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: clientes; Type: TABLE; Schema: public; Owner: bpuser
--

CREATE TABLE public.clientes (
    id bigint NOT NULL,
    cliente_id character varying(255) NOT NULL,
    contrasena character varying(255) NOT NULL,
    direccion character varying(255) NOT NULL,
    edad integer NOT NULL,
    estado boolean NOT NULL,
    genero character varying(255) NOT NULL,
    identificacion character varying(255) NOT NULL,
    nombre character varying(255) NOT NULL,
    telefono character varying(255) NOT NULL
);


ALTER TABLE public.clientes OWNER TO bpuser;

--
-- Name: clientes_id_seq; Type: SEQUENCE; Schema: public; Owner: bpuser
--

ALTER TABLE public.clientes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.clientes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cuentas; Type: TABLE; Schema: public; Owner: bpuser
--

CREATE TABLE public.cuentas (
    id bigint NOT NULL,
    cliente_id bigint NOT NULL,
    estado boolean NOT NULL,
    numero_cuenta character varying(255) NOT NULL,
    saldo_disponible double precision NOT NULL,
    saldo_inicial double precision NOT NULL,
    tipo_cuenta character varying(255) NOT NULL
);


ALTER TABLE public.cuentas OWNER TO bpuser;

--
-- Name: cuentas_id_seq; Type: SEQUENCE; Schema: public; Owner: bpuser
--

ALTER TABLE public.cuentas ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cuentas_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: movimientos; Type: TABLE; Schema: public; Owner: bpuser
--

CREATE TABLE public.movimientos (
    id bigint NOT NULL,
    cuenta_id bigint NOT NULL,
    fecha timestamp(6) without time zone NOT NULL,
    saldo double precision NOT NULL,
    tipo_movimiento character varying(255) NOT NULL,
    valor double precision NOT NULL
);


ALTER TABLE public.movimientos OWNER TO bpuser;

--
-- Name: movimientos_id_seq; Type: SEQUENCE; Schema: public; Owner: bpuser
--

ALTER TABLE public.movimientos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.movimientos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: clientes clientes_pkey; Type: CONSTRAINT; Schema: public; Owner: bpuser
--

ALTER TABLE ONLY public.clientes
    ADD CONSTRAINT clientes_pkey PRIMARY KEY (id);


--
-- Name: cuentas cuentas_pkey; Type: CONSTRAINT; Schema: public; Owner: bpuser
--

ALTER TABLE ONLY public.cuentas
    ADD CONSTRAINT cuentas_pkey PRIMARY KEY (id);


--
-- Name: movimientos movimientos_pkey; Type: CONSTRAINT; Schema: public; Owner: bpuser
--

ALTER TABLE ONLY public.movimientos
    ADD CONSTRAINT movimientos_pkey PRIMARY KEY (id);


--
-- Name: cuentas uk7h7mqvcau3mcl0mbrkdrt7fnh; Type: CONSTRAINT; Schema: public; Owner: bpuser
--

ALTER TABLE ONLY public.cuentas
    ADD CONSTRAINT uk7h7mqvcau3mcl0mbrkdrt7fnh UNIQUE (numero_cuenta);


--
-- Name: clientes ukmvqpaay4xno9pnlalro0awadi; Type: CONSTRAINT; Schema: public; Owner: bpuser
--

ALTER TABLE ONLY public.clientes
    ADD CONSTRAINT ukmvqpaay4xno9pnlalro0awadi UNIQUE (identificacion);


--
-- Name: clientes uknhdbltv7dnhp65s6wjb411goq; Type: CONSTRAINT; Schema: public; Owner: bpuser
--

ALTER TABLE ONLY public.clientes
    ADD CONSTRAINT uknhdbltv7dnhp65s6wjb411goq UNIQUE (cliente_id);


--
-- PostgreSQL database dump complete
--

\unrestrict RMLZ6aAhBhVduGSDp9MwqVJYyhfMoVQ2HVO6HeZ9xLMViYdOC1jXA2EX6ZSJ5sl

